### PR TITLE
hot fix

### PR DESCRIPTION
**Pull request by Notplayingallday383**
Applied Hot-Fix from Official Terbium

### CODE REVIEW

**Comment by Notplayingallday383** [comment]
pushing new release to fork: Terbium WebOS by z1g Project

**Comment by dragonballls** [comment]
rehehehehhehehehehheheheheheeh

**Comment by dragonballls** [comment]
can u make a proxy that unblocks now.gg

**Comment by dragonballls** [comment]
terbium isnt working

**Comment by Notplayingallday383** [comment]
Thanks for your feedback I will see what I can do about the Now.gg proxy but Terbium should be working right now because I had to restart the server any other issues please tell us in the [Issues](https://github.com/z1g-project/Terbium/issues) section for easier access

**Comment by Notplayingallday383** [comment]
shut the fuck up

**Pull request closed without merging**
